dependencies:
- alias: ttc-campaigns-service
  name: "activiti-cloud-connector"
  repository: "https://activiti.github.io/activiti-cloud-charts/"
  version: "0.8.0"
- alias: ttc-connectors-dummytwitter
  name: "activiti-cloud-connector"
  repository: "https://activiti.github.io/activiti-cloud-charts/"
  version: "0.8.0"
- alias: ttc-connectors-processing
  name: "activiti-cloud-connector"
  repository: "https://activiti.github.io/activiti-cloud-charts/"
  version: "0.8.0"
- alias: ttc-connectors-ranking
  name: "activiti-cloud-connector"
  repository: "https://activiti.github.io/activiti-cloud-charts/"
  version: "0.8.0"
- alias: ttc-connectors-reward
  name: "activiti-cloud-connector"
  repository: "https://activiti.github.io/activiti-cloud-charts/"
  version: "0.8.0"
- alias: ttc-query-campaign
  name: "activiti-cloud-query"
  repository: "https://activiti.github.io/activiti-cloud-charts/"
  version: "0.8.0"
- alias: ttc-rb-english-campaign
  name: "runtime-bundle"
  repository: "https://activiti.github.io/activiti-cloud-charts/"
  version: "0.8.0"
- name: infrastructure
  repository: "https://activiti.github.io/activiti-cloud-charts/"
  version: "0.8.0"
- name: application
  repository: "https://activiti.github.io/activiti-cloud-charts/"
  version: "0.8.0"