dependencies:
- alias: ttc-campaigns-service
  name: "activiti-cloud-connector"
  repository: "https://activiti.github.io/activiti-cloud-charts/"
  version: "0.8.0"
- alias: ttc-connectors-dummytwitter
  name: "activiti-cloud-connector"
  repository: "https://activiti.github.io/activiti-cloud-charts/"
  version: "0.8.0"
- alias: ttc-connectors-processing
  name: "activiti-cloud-connector"
  repository: "https://activiti.github.io/activiti-cloud-charts/"
  version: "0.8.0"
- alias: ttc-connectors-ranking
  name: "activiti-cloud-connector"
  repository: "https://activiti.github.io/activiti-cloud-charts/"
  version: "0.8.0"
- alias: ttc-connectors-reward
  name: "activiti-cloud-connector"
  repository: "https://activiti.github.io/activiti-cloud-charts/"
  version: "0.8.0"
- alias: ttc-query-campaign
  name: "activiti-cloud-query"
  repository: "https://activiti.github.io/activiti-cloud-charts/"
  version: "0.8.0"
- alias: ttc-rb-english-campaign
  name: "runtime-bundle"
  repository: "https://activiti.github.io/activiti-cloud-charts/"
  version: "0.8.0"
- alias: rabbitmq
  name: rabbitmq-ha
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 1.6.2
  condition: application.rabbitmq.enabled,rabbitmq.enabled
- alias: postgres
  name: postgresql
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 0.11.0
  condition: application.postgres.enabled,postgres.enabled  
- name: activiti-keycloak
  repository: https://activiti.github.io/activiti-cloud-charts/
  version: 0.2.0
  condition: infrastructure.activiti-keycloak.enabled,activiti-keycloak.enabled
- name: activiti-cloud-gateway
  repository: https://activiti.github.io/activiti-cloud-charts/
  version: 0.8.0
  condition: infrastructure.activiti-cloud-gateway.enabled,activiti-cloud-gateway.enabled
 